version: '3'
services:
  nwserver:
    hostname: nwserver
    stop_signal: SIGINT
    image: nwnxee/unified:build8193.35.40
    env_file: ${PWD-.}/config/nwserver.env
    stdin_open: true
    tty: true
    volumes:
      - ${PWD-.}/logs:/nwn/run/logs.0
      - ${PWD-.}/server/:/nwn/home
    restart: unless-stopped
    ports:
      - "5121:5121/udp"

