module:
  # module to unpack 
  from: C:\Users\j_rid\Documents\Neverwinter Nights\modules\Lands of Intrigue Alpha v0_1_15.mod
  # desired file to pack module to
  to: server\modules\Lands of Intrigue Alpha TEST.mod

# do not change these
root: src
temp: src\temporary