module:
  # module to unpack 
  from: loi-alpha-my-work.mod
  # desired file to pack module to
  # to: server/modules/loi-alpha-test.mod
  to: server/modules/loi-alpha-test.mod

# what operating system (win|linux|macos)
os: win

# do not change these
root: src
temp: src/temporary