name: build-tethyr
run-name: ${{ github.actor }} triggered Lands of Intrigue Tethyr build
on:
  push:
    branches:
      - 'main'
jobs:
  module:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Update python dependencies
        run: pip install pyyaml
      - name: Prepare target folder
        run: mkdir server\modules
      - name: Build module
        run: python module_packer.py pack
      - name: Upload artifact
        uses: actions/upload-artifact@v1
        with:
          name: loi-alpha-test_${{ github.head_ref }}.${{ github.sha }}.mod
          path: server\modules\loi-alpha-test.mod
